language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --no-progress --no-scripts --no-suggest --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --standard=PSR12 src/ tests/
