language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer update --no-progress --no-scripts --no-suggest --no-interaction --prefer-stable $PREFER_LOWEST

script:
  - vendor/bin/phpcs --standard=PSR12 src/ tests/
  - vendor/bin/phpstan analyse --no-progress --no-ansi --no-interaction
  - vendor/bin/phpunit --no-interaction --colors=never
